services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundles\DemoBundle\src\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests}'

    App\Bundles\DemoBundle\EventListener\QuoteViewedListener:
        tags:
            - { name: kernel.event_listener, event: quote.viewed, method: onQuoteViewed }
